repos:
  - repo: local
    hooks:
      - id: cargo-test
        name: cargo test
        entry: cargo test
        language: system
        stages: [pre-push]

      - id: cargo-check-fmt
        name: cargo check and format
        entry: sh -c 'cargo check && cargo fmt --all --check'
        language: system
        stages: [pre-commit]

      - id: commit-msg
        name: commitlint
        entry: commitlint --edit
        language: system
        stages: [commit-msg]