repos:
  - repo: local
    hooks:
      - id: commit-msg
        name: commitlint
        entry: commitlint --edit
        language: system
        stages: [commit-msg]
      
      - id: cargo-fmt
        name: cargo format
        entry: cargo fmt
        language: system
        args: ["--", "--check"]
        types: [rust]
        stages: [pre-commit]
      
      - id: cargo-clippy
        name: cargo clippy
        description: Lint rust sources
        entry: cargo clippy
        language: system
        args: ["--", "-D", "warnings"]
        types: [rust]
        pass_filenames: false
        stages: [pre-commit]

      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-commit]

      - id: cargo-test
        name: cargo test
        description: Checking tests for errors.
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-push]