[package]
name = "zk-auctions-protocols"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.4.6", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
zk-auctions-core = { path = "../core" }
rand = "0.8.5"
num-traits = "0.2.19"

