[package]
name = "zk-auctions-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false }
rand = "0.8.5"
rug = "1.26.1"
sha2 = "0.10.8"
num-bigint = "0.4.6"
num-iter = "0.1.45"
num-traits = "0.2.19"
num-integer = "0.1.46"