[package]
name = "probabilistic-encryption"
version = "0.1.0"
authors = ["Carlos Rodriguez-Vega <crodveg@yahoo.es>"]
edition = "2018"
src = "https://github.com/crodriguezvega/probabilisticpubkey?tab=readme-ov-file"

[dependencies]
bitvec = "0.20"
failure = "0.1.5"
num-bigint = { version = "0.4.6", features = ["rand"]}
num-integer = "0.1"
num-traits = "0.2"
primal = "0.3.0"
rand = "0.8.5"

[dev-dependencies]
proptest = "0.10.1"

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    ".cargo/registry/src/github.com-1ecc6299db9ec823/katex-doc-0.1.0/katex.html",
]