[package]
name = "circuits"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "=0.10"
serde = { version = "=1.0", default-features = false, features = ["derive"] }
serde_json = "=1.0"
rand = "=0.8"
clap = { version = "=4.0", features = ["derive"] }
clap-num = "=1.0.2"
cli = { path = "../cli" }

# halo2
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_02_02" }

# Axiom's helper API with basic functions
halo2-base = { git = "https://github.com/axiom-crypto/halo2-lib", branch = "community-edition" }
snark-verifier-sdk = { git = "https://github.com/axiom-crypto/snark-verifier.git", branch = "community-edition" }

[dev-dependencies]
test-log = "=0.2.11"
ethers-core = "=2.0.6"

[features]
default = []
