[package]
name = "circuits"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
anyhow = "1.0.81"
env_logger = "=0.10"
serde = { version = "=1.0", default-features = false, features = ["derive"] }
serde_json = "=1.0"
rand = "=0.8"
clap = { version = "=4.0", features = ["derive"] }
clap-num = "=1.0.2"
cli = { path = "../cli" }
probabilistic-encryption = { path = "../probabilistic-encryption" }
num-bigint = "0.4.4"

# halo2
halo2-ecc = { version = "0.4.1", default-features = false, features = ["halo2-axiom"] }
halo2-base = { version = "0.4.1", default-features = false, features = ["halo2-axiom"] }
halo2-wasm = { version = "0.3.4" }
wasm-bindgen = "0.2.89"
snark-verifier-sdk = { git = "https://github.com/axiom-crypto/snark-verifier.git", branch = "community-edition" }

[dev-dependencies]
test-log = "=0.2.11"
ethers-core = "=2.0.6"

[features]
default = []
