// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
extern crate risc0_zkvm;

fn main() {
    println!("Verifying ...",);
}
