name: Static Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']
  push:
    branches: [main, staging]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Clone submodule up to the origin latest changes
        run: git submodule foreach --recursive git reset --hard || echo "Submodule update failed, attempting manual clone..."
        
      - name: Apply Patch Changes to the submodule
        run: |
          cd packages/probabilistic-encryption
          git am ../../submodules-changes.patch || echo "No patch file found or no changes to apply"
        
      - uses: actions/setup-python@v4

      - name: Install Rust toolchain 1.74 (with clippy and rustfmt)
        run: rustup toolchain install nightly-2023-12-21 && rustup component add clippy --toolchain nightly-2023-12-21 && rustup component add rustfmt --toolchain nightly-2023-12-21

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
          
