name: Static Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']
  push:
    branches: [main, staging]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Attempt Submodule Update (ignore errors)
        run: git submodule update --init --recursive || echo "Submodule update failed, attempting manual clone..."

      - name: Manual Submodule Clone (if needed)
        run: |
          if [ ! -d "packages/probabilistic-encryption" ]; then
            git clone https://github.com/crodriguezvega/probabilisticpubkey packages/probabilistic-encryption
            cd packages/probabilistic-encryption
            git checkout master
          fi

      - name: Apply Patch Changes
        run: git apply ../../submodules-changes.patch || echo "No patch file found or no changes to apply"
        
      - uses: actions/setup-python@v4

      - name: Install Rust toolchain 1.74 (with clippy and rustfmt)
        run: rustup toolchain install nightly-2023-12-21 && rustup component add clippy --toolchain nightly-2023-12-21 && rustup component add rustfmt --toolchain nightly-2023-12-21

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
          
