name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']
  push:
    branches: [main, staging]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      # Install Rust toolchain and components
      - name: Install Rust with Clippy and Rustfmt
        run: |
          rustup install nightly
          rustup default nightly
          rustup override set nightly
          rustup component add clippy
          rustup component add rustfmt
          curl -L https://risczero.com/install | bash
          ~/.risc0/bin/rzup install
          cargo risczero --version

      - name: Run tests
        run: cargo test
