name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']
  push:
    branches: [main, staging]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Clone submodules
        run: git submodule update --init --recursive
        
      - name: Set Git Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Apply Patch Changes to the submodule
        run: |
          cd packages/probabilistic-encryption
          git apply ../../submodules-changes.patch

      - uses: actions/setup-python@v4

      - name: Install Rust toolchain 1.74 (with clippy and rustfmt)
        run: rustup toolchain install nightly-2023-12-21 && rustup component add clippy --toolchain nightly-2023-12-21 && rustup component add rustfmt --toolchain nightly-2023-12-21

      - name: Run tests
        run: cargo test
          