name: Test Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']
  push:
    branches: [main, staging]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly (edition 2024 support)
        run: |
          rustup install nightly
          rustup default nightly

      - name: Set Rust nightly for edition 2024
        run: rustup override set nightly

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run tests with coverage
        run: cargo llvm-cov --all-features --workspace --html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/llvm-cov/html/
