name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']
  push:
    branches: [main, staging]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      # Install Rust toolchain and components
      - name: Install Rust toolchain (nightly-2023-12-21) with Clippy and Rustfmt
        run: |
          rustup toolchain install nightly-2023-12-21
          rustup component add clippy --toolchain nightly-2023-12-21
          rustup component add rustfmt --toolchain nightly-2023-12-21
          curl -L https://risczero.com/install | bash
          rzup install
          cargo risczero --version

      - name: Run tests
        run: cargo test
